# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

auto: true # automatically update your jekyll
server: true # runs a local server
paginate: 10 # pagination basted on number of posts
exclude: ["README.md"] # files to exclude

title: dbyll
author:
  name: dbyll
  email: dbyll@ismaildemirbilek.com
  github: asd123
  twitter: asd123
  pinterest: asd123
  linkedin: asd123
  resume: asd123
  bio: Your stylish, minimalist theme!
  email_md5: 726351295ec82e145928582f595aa3aa
  
BASE_PATH: http://dbtek.github.io/dbyll
